### ISSUE TITLE
怎样限制后台下载时的下载并发数

### ISSUE THREAD

**Issue by CodeisSunShine** [dqfeng/DQDownloadManager#1]
您好，很惊喜的看到了您的demo，但是我在试验中发现在后台下载的过程中，多个task会被下载，于是我设置了configuration.HTTPMaximumConnectionsPerHost = 1;但是遗憾的是无效的，所以想请教您一下是否有其他的方式控制后台下载时的并发数

**Comment by dqfeng** [comment]
您好！很高兴你能对该项目提出问题，最近一直很忙刚看到，在本项目中控制下载并发数可以通过设置DQDownloadManager的concurrentDownloadingCount属性，但是这个设置只对前台有效，是因为考虑到当有任务下载完成后应该启动一个等待中的下载任务，但是在后台状态下有任务下载完成时不会执行下载完成的回调，所以一直处在后台状态下等待中的任务是得不到恢复的。为了解决这个问题我在应用进入后台后将所有等待中的任务也开启了，也就造成你看到在后台状态下会有多个task被下载的情况。configuration.HTTPMaximumConnectionsPerHost 是可以控制一个host下同时并发链接数的，你是不是调用的时机不对？

**Comment by CodeisSunShine** [comment]
我是在创建session的时候 设置configuration.HTTPMaximumConnectionsPerHost = 1，能请教您正确的调用时机吗。
